-- DC Comics Action Figures Database v2 — Historical (1972–2023)
-- Run: mysql -u root -p < schema_v2.sql

CREATE DATABASE IF NOT EXISTS dc_figures;
USE dc_figures;

DROP TABLE IF EXISTS figures;

CREATE TABLE figures (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(120)  NOT NULL,
  character     VARCHAR(100)  NOT NULL,
  series        VARCHAR(100)  NOT NULL,
  manufacturer  VARCHAR(80)   NOT NULL,
  year          YEAR          NOT NULL,
  era           VARCHAR(40)   NOT NULL,  -- e.g. 'Mego Era','Super Powers Era'
  scale         VARCHAR(20)   NOT NULL,
  universe      ENUM('Classic','Silver Age','Bronze Age','Modern Age','Animated','Movie','Elseworlds','New 52','Rebirth','Dark Multiverse') NOT NULL,
  rarity        ENUM('Common','Uncommon','Rare','Ultra Rare') NOT NULL,
  price_usd     DECIMAL(8,2)  NOT NULL,
  in_stock      BOOLEAN       NOT NULL DEFAULT TRUE,
  accessories   TEXT,
  INDEX idx_character   (character),
  INDEX idx_era         (era),
  INDEX idx_year        (year),
  INDEX idx_rarity      (rarity),
  INDEX idx_universe    (universe),
  INDEX idx_manufacturer(manufacturer)
);

INSERT INTO figures (name,character,series,manufacturer,year,era,scale,universe,rarity,price_usd,in_stock,accessories) VALUES
-- ════════════════════════════════════════
-- MEGO ERA  1972–1982
-- ════════════════════════════════════════
('Batman World Greatest Super Heroes','Batman','World Greatest Super Heroes','Mego',1972,'Mego Era','8-inch','Bronze Age','Ultra Rare',189.99,FALSE,'Cloth costume, cape, batarang'),
('Superman World Greatest Super Heroes','Superman','World Greatest Super Heroes','Mego',1972,'Mego Era','8-inch','Bronze Age','Ultra Rare',179.99,FALSE,'Cloth costume, cape'),
('Aquaman World Greatest Super Heroes','Aquaman','World Greatest Super Heroes','Mego',1972,'Mego Era','8-inch','Bronze Age','Ultra Rare',169.99,FALSE,'Cloth costume, trident'),
('Robin World Greatest Super Heroes','Robin','World Greatest Super Heroes','Mego',1973,'Mego Era','8-inch','Bronze Age','Ultra Rare',159.99,FALSE,'Cloth costume, cape'),
('Wonder Woman World Greatest Super Heroes','Wonder Woman','World Greatest Super Heroes','Mego',1974,'Mego Era','8-inch','Bronze Age','Ultra Rare',174.99,FALSE,'Cloth costume, lasso, tiara'),
('Green Arrow World Greatest Super Heroes','Green Arrow','World Greatest Super Heroes','Mego',1975,'Mego Era','8-inch','Bronze Age','Ultra Rare',189.99,FALSE,'Cloth costume, bow, quiver'),
('Shazam World Greatest Super Heroes','Shazam','World Greatest Super Heroes','Mego',1975,'Mego Era','8-inch','Bronze Age','Ultra Rare',169.99,FALSE,'Cloth costume'),
('Joker World Greatest Super Heroes','The Joker','World Greatest Super Heroes','Mego',1974,'Mego Era','8-inch','Bronze Age','Ultra Rare',199.99,FALSE,'Cloth costume, accessories'),
('Catwoman World Greatest Super Heroes','Catwoman','World Greatest Super Heroes','Mego',1975,'Mego Era','8-inch','Bronze Age','Ultra Rare',219.99,FALSE,'Cloth costume, whip'),
('Riddler World Greatest Super Heroes','The Riddler','World Greatest Super Heroes','Mego',1975,'Mego Era','8-inch','Bronze Age','Ultra Rare',209.99,FALSE,'Cloth costume, cane'),
('Penguin World Greatest Super Heroes','The Penguin','World Greatest Super Heroes','Mego',1975,'Mego Era','8-inch','Bronze Age','Ultra Rare',199.99,FALSE,'Cloth costume, umbrella'),
('Flash World Greatest Super Heroes','The Flash','World Greatest Super Heroes','Mego',1979,'Mego Era','8-inch','Bronze Age','Ultra Rare',189.99,FALSE,'Cloth costume'),
('Green Lantern World Greatest Super Heroes','Green Lantern','World Greatest Super Heroes','Mego',1976,'Mego Era','8-inch','Bronze Age','Ultra Rare',194.99,FALSE,'Cloth costume, ring'),
('Lex Luthor World Greatest Super Heroes','Lex Luthor','World Greatest Super Heroes','Mego',1980,'Mego Era','8-inch','Bronze Age','Ultra Rare',189.99,FALSE,'Cloth costume, kryptonite'),
('Teen Titans Speedy Mego','Speedy','Teen Titans','Mego',1976,'Mego Era','8-inch','Bronze Age','Ultra Rare',229.99,FALSE,'Cloth costume, bow, quiver'),
('Teen Titans Wonder Girl Mego','Wonder Girl','Teen Titans','Mego',1976,'Mego Era','8-inch','Bronze Age','Ultra Rare',249.99,FALSE,'Cloth costume, lasso'),
-- ════════════════════════════════════════
-- KENNER SUPER POWERS  1984–1986
-- ════════════════════════════════════════
('Superman Super Powers','Superman','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',44.99,FALSE,'Cape, mini-comic'),
('Batman Super Powers','Batman','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',49.99,FALSE,'Mini-comic, batarang'),
('Robin Super Powers','Robin','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',44.99,FALSE,'Mini-comic'),
('Wonder Woman Super Powers','Wonder Woman','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',44.99,FALSE,'Lasso, mini-comic'),
('The Flash Super Powers','The Flash','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',44.99,FALSE,'Mini-comic'),
('Green Lantern Super Powers','Green Lantern','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',49.99,FALSE,'Lantern, ring, mini-comic'),
('Aquaman Super Powers','Aquaman','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',44.99,FALSE,'Trident, mini-comic'),
('Hawkman Super Powers','Hawkman','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',54.99,FALSE,'Wings, mace, mini-comic'),
('The Joker Super Powers','The Joker','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',49.99,FALSE,'Mallet, mini-comic'),
('Lex Luthor Super Powers','Lex Luthor','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',44.99,FALSE,'Mini-comic'),
('Brainiac Super Powers','Brainiac','Super Powers Collection','Kenner',1984,'Super Powers Era','4.5-inch','Classic','Rare',54.99,FALSE,'Mini-comic, accessories'),
('Penguin Super Powers','The Penguin','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Rare',49.99,FALSE,'Umbrella, mini-comic'),
('Darkseid Super Powers','Darkseid','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Ultra Rare',79.99,FALSE,'Mini-comic, Omega Effect stand'),
('Desaad Super Powers','Desaad','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Ultra Rare',74.99,FALSE,'Mini-comic'),
('Kalibak Super Powers','Kalibak','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Ultra Rare',69.99,FALSE,'Beta Club, mini-comic'),
('Parademon Super Powers','Parademon','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Rare',54.99,FALSE,'Mini-comic'),
('Mantis Super Powers','Mantis','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Rare',54.99,FALSE,'Mini-comic'),
('Green Arrow Super Powers','Green Arrow','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Rare',54.99,FALSE,'Bow, quiver, mini-comic'),
('Firestorm Super Powers','Firestorm','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Rare',54.99,FALSE,'Mini-comic'),
('Red Tornado Super Powers','Red Tornado','Super Powers Collection','Kenner',1985,'Super Powers Era','4.5-inch','Classic','Rare',59.99,FALSE,'Mini-comic'),
('Shazam Super Powers','Shazam','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',64.99,FALSE,'Cape, mini-comic'),
('Mr. Freeze Super Powers','Mr. Freeze','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',84.99,FALSE,'Dome, freeze gun, mini-comic'),
('Cyborg Super Powers','Cyborg','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',74.99,FALSE,'Interchangeable arms, mini-comic'),
('Mr. Miracle Super Powers','Mr. Miracle','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',79.99,FALSE,'Cape, shackles, mini-comic'),
('Orion Super Powers','Orion','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',74.99,FALSE,'Mini-comic'),
('Samurai Super Powers','Samurai','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',89.99,FALSE,'Sword, removable vest, mini-comic'),
('Tyr Super Powers','Tyr','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',94.99,FALSE,'Gun-hand, mini-comic'),
('Golden Pharaoh Super Powers','Golden Pharaoh','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',99.99,FALSE,'Staff, wings, mini-comic'),
('Cyclotron Super Powers','Cyclotron','Super Powers Collection','Kenner',1986,'Super Powers Era','4.5-inch','Classic','Ultra Rare',99.99,FALSE,'Removable faceplate, mini-comic'),
-- ════════════════════════════════════════
-- TOY BIZ DC SUPER HEROES  1989–1991
-- ════════════════════════════════════════
('Batman DC Super Heroes','Batman','DC Comics Super Heroes','Toy Biz',1989,'DC Super Heroes Era','5-inch','Classic','Uncommon',29.99,FALSE,'Display stand'),
('Superman DC Super Heroes','Superman','DC Comics Super Heroes','Toy Biz',1989,'DC Super Heroes Era','5-inch','Classic','Uncommon',24.99,FALSE,'Display stand'),
('Wonder Woman DC Super Heroes','Wonder Woman','DC Comics Super Heroes','Toy Biz',1989,'DC Super Heroes Era','5-inch','Classic','Uncommon',24.99,FALSE,'Lasso, display stand'),
('Joker DC Super Heroes','The Joker','DC Comics Super Heroes','Toy Biz',1989,'DC Super Heroes Era','5-inch','Classic','Uncommon',29.99,FALSE,'Display stand'),
('Penguin DC Super Heroes','The Penguin','DC Comics Super Heroes','Toy Biz',1990,'DC Super Heroes Era','5-inch','Classic','Uncommon',27.99,FALSE,'Umbrella, display stand'),
('Two-Face DC Super Heroes','Two-Face','DC Comics Super Heroes','Toy Biz',1990,'DC Super Heroes Era','5-inch','Classic','Uncommon',27.99,FALSE,'Coin, display stand'),
('Green Lantern DC Super Heroes','Green Lantern','DC Comics Super Heroes','Toy Biz',1990,'DC Super Heroes Era','5-inch','Classic','Uncommon',27.99,FALSE,'Ring, display stand'),
('The Flash DC Super Heroes','The Flash','DC Comics Super Heroes','Toy Biz',1990,'DC Super Heroes Era','5-inch','Classic','Uncommon',24.99,FALSE,'Display stand'),
('Robin DC Super Heroes','Robin','DC Comics Super Heroes','Toy Biz',1990,'DC Super Heroes Era','5-inch','Classic','Uncommon',24.99,FALSE,'Display stand'),
-- ════════════════════════════════════════
-- KENNER BATMAN ANIMATED SERIES  1992–1997
-- ════════════════════════════════════════
('Batman BTAS Series 1','Batman','Batman: The Animated Series','Kenner',1992,'Animated Era','5-inch','Animated','Uncommon',24.99,FALSE,'Batarang, grapple gun'),
('Joker BTAS Series 1','The Joker','Batman: The Animated Series','Kenner',1992,'Animated Era','5-inch','Animated','Uncommon',27.99,FALSE,'Mallet, pie gun'),
('Two-Face BTAS','Two-Face','Batman: The Animated Series','Kenner',1992,'Animated Era','5-inch','Animated','Uncommon',24.99,FALSE,'Coin, pistol'),
('Catwoman BTAS','Catwoman','Batman: The Animated Series','Kenner',1992,'Animated Era','5-inch','Animated','Uncommon',24.99,FALSE,'Whip'),
('Robin BTAS','Robin','Batman: The Animated Series','Kenner',1992,'Animated Era','5-inch','Animated','Uncommon',22.99,FALSE,'Staff'),
('Poison Ivy BTAS','Poison Ivy','Batman: The Animated Series','Kenner',1993,'Animated Era','5-inch','Animated','Rare',34.99,FALSE,'Vine accessories'),
('Scarecrow BTAS','Scarecrow','Batman: The Animated Series','Kenner',1993,'Animated Era','5-inch','Animated','Uncommon',24.99,FALSE,'Fear gun'),
('Riddler BTAS','The Riddler','Batman: The Animated Series','Kenner',1993,'Animated Era','5-inch','Animated','Uncommon',24.99,FALSE,'Cane, riddle card'),
('Mr. Freeze BTAS','Mr. Freeze','Batman: The Animated Series','Kenner',1993,'Animated Era','5-inch','Animated','Rare',29.99,FALSE,'Freeze gun, ice sled'),
('Harley Quinn BTAS','Harley Quinn','Batman: The Animated Series','Kenner',1994,'Animated Era','5-inch','Animated','Rare',39.99,FALSE,'Mallet, confetti gun'),
('Clayface BTAS','Clayface','Batman: The Animated Series','Kenner',1994,'Animated Era','5-inch','Animated','Rare',34.99,FALSE,'Clay projectile'),
('Batman Phantasm Mask of the Phantasm','Batman','Batman: Mask of the Phantasm','Kenner',1993,'Animated Era','5-inch','Animated','Rare',39.99,FALSE,'Phantasm mask, cape'),
('Penguin BTAS','The Penguin','Batman: The Animated Series','Kenner',1993,'Animated Era','5-inch','Animated','Uncommon',24.99,FALSE,'Umbrella, fish'),
('Nightwing BTAS','Nightwing','Batman: The Animated Series','Kenner',1995,'Animated Era','5-inch','Animated','Rare',34.99,FALSE,'Escrima sticks'),
-- ════════════════════════════════════════
-- KENNER TOTAL JUSTICE  1996–1997
-- ════════════════════════════════════════
('Batman Total Justice','Batman','Total Justice','Kenner',1996,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Fractal tech armor'),
('Superman Total Justice','Superman','Total Justice','Kenner',1996,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Fractal tech armor'),
('Green Lantern Total Justice','Green Lantern','Total Justice','Kenner',1996,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Fractal tech armor, ring'),
('The Flash Total Justice','The Flash','Total Justice','Kenner',1996,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Fractal tech armor'),
('Aquaman Total Justice','Aquaman','Total Justice','Kenner',1996,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Trident, fractal armor'),
('Hawkman Total Justice','Hawkman','Total Justice','Kenner',1996,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Wings, mace, fractal armor'),
('Green Arrow Total Justice','Green Arrow','Total Justice','Kenner',1996,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Bow, quiver, fractal armor'),
('Robin Total Justice','Robin','Total Justice','Kenner',1997,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Fractal tech armor'),
('Wonder Woman Total Justice','Wonder Woman','Total Justice','Kenner',1997,'Total Justice Era','5-inch','Classic','Uncommon',19.99,FALSE,'Fractal tech armor, lasso'),
('Despero Total Justice','Despero','Total Justice','Kenner',1997,'Total Justice Era','5-inch','Classic','Rare',24.99,FALSE,'Fractal armor'),
('Parallax Total Justice','Parallax','Total Justice','Kenner',1997,'Total Justice Era','5-inch','Classic','Rare',29.99,FALSE,'Fractal armor, energy construct'),
-- ════════════════════════════════════════
-- DC DIRECT / DC COLLECTIBLES  1998–2011
-- ════════════════════════════════════════
('Batman Hush DC Direct Series 1','Batman','Batman: Hush','DC Direct',2004,'DC Direct Era','6.75-inch','Modern Age','Rare',44.99,FALSE,'Batarang, grapple gun, stand'),
('Joker Hush DC Direct','The Joker','Batman: Hush','DC Direct',2004,'DC Direct Era','6.75-inch','Modern Age','Rare',44.99,FALSE,'Gun, stand'),
('Catwoman Hush DC Direct','Catwoman','Batman: Hush','DC Direct',2004,'DC Direct Era','6.75-inch','Modern Age','Rare',39.99,FALSE,'Whip, goggles, stand'),
('Superman All Star DC Direct','Superman','All Star Superman','DC Direct',2008,'DC Direct Era','6.75-inch','Modern Age','Rare',39.99,FALSE,'Kryptonian key, stand'),
('Batman Alex Ross DC Direct','Batman','Batman: Mythology','DC Direct',2003,'DC Direct Era','6.75-inch','Modern Age','Rare',44.99,FALSE,'Batarang, stand'),
('Superman Alex Ross DC Direct','Superman','Kingdom Come','DC Direct',2003,'DC Direct Era','6.75-inch','Elseworlds','Ultra Rare',54.99,FALSE,'Kryptonite, stand'),
('Wonder Woman Alex Ross DC Direct','Wonder Woman','Kingdom Come','DC Direct',2003,'DC Direct Era','6.75-inch','Elseworlds','Ultra Rare',49.99,FALSE,'Lasso, stand'),
('Kingdom Come Batman DC Direct','Batman','Kingdom Come','DC Direct',2003,'DC Direct Era','6.75-inch','Elseworlds','Ultra Rare',59.99,FALSE,'Exo-suit, stand'),
('Flash Rebirth Ethan Van Sciver DC Direct','The Flash','Flash: Rebirth','DC Direct',2010,'DC Direct Era','6.75-inch','Modern Age','Rare',44.99,FALSE,'Speed force construct, stand'),
('Green Lantern Secret Origin DC Direct','Green Lantern','Green Lantern: Secret Origin','DC Direct',2009,'DC Direct Era','6.75-inch','Modern Age','Rare',44.99,FALSE,'Power ring, lantern, stand'),
('Batman Dark Victory DC Direct','Batman','Batman: Dark Victory','DC Direct',2002,'DC Direct Era','6.75-inch','Modern Age','Rare',44.99,FALSE,'Batarang, stand'),
('Harley Quinn Batman Mad Love DC Direct','Harley Quinn','Batman: Mad Love','DC Direct',2000,'DC Direct Era','6.75-inch','Animated','Ultra Rare',74.99,FALSE,'Mallet, BANG! gun, stand'),
('Poison Ivy DC Direct Series 1','Poison Ivy','DC Direct Series 1','DC Direct',1999,'DC Direct Era','6.75-inch','Modern Age','Ultra Rare',69.99,FALSE,'Vine wrap, stand'),
('Batman Knightfall DC Direct','Batman','Batman: Knightfall','DC Direct',2005,'DC Direct Era','6.75-inch','Modern Age','Rare',49.99,FALSE,'Batarang, grapple gun, stand'),
('Bane Knightfall DC Direct','Bane','Batman: Knightfall','DC Direct',2005,'DC Direct Era','6.75-inch','Modern Age','Rare',49.99,FALSE,'Venom tube, stand'),
('Superman Death of Superman DC Direct','Superman','Death of Superman','DC Direct',2003,'DC Direct Era','6.75-inch','Modern Age','Rare',54.99,FALSE,'Display stand, cape'),
('Doomsday DC Direct','Doomsday','Death of Superman','DC Direct',2003,'DC Direct Era','6.75-inch','Modern Age','Rare',54.99,FALSE,'Display stand'),
-- ════════════════════════════════════════
-- MATTEL DC UNIVERSE CLASSICS  2008–2013
-- ════════════════════════════════════════
('Batman DCUC Wave 1','Batman','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Batarang, C&C Metamorpho part'),
('Superman DCUC Wave 2','Superman','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'C&C Grundy part'),
('Wonder Woman DCUC Wave 4','Wonder Woman','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Sword, shield, C&C Despero part'),
('The Flash Wally West DCUC','The Flash','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'C&C Grodd part'),
('Green Lantern Hal Jordan DCUC','Green Lantern','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Power ring construct, C&C part'),
('Aquaman DCUC Wave 2','Aquaman','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Trident, C&C part'),
('Robin Tim Drake DCUC','Robin','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Staff, C&C part'),
('Nightwing DCUC Wave 3','Nightwing','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Escrima sticks, C&C part'),
('Black Canary DCUC Wave 4','Black Canary','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Sonic scream effect, C&C part'),
('Martian Manhunter DCUC Wave 5','Martian Manhunter','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'C&C Metallo part'),
('Hawkman DCUC Wave 6','Hawkman','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Wings, mace, C&C part'),
('Shazam DCUC Wave 7','Shazam','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'C&C STRIPE part'),
('Green Arrow DCUC Wave 9','Green Arrow','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Bow, quiver, C&C part'),
('Joker DCUC Wave 10','The Joker','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Flower, C&C Imperiex part'),
('Two-Face DCUC Wave 15','Two-Face','DC Universe Classics','Mattel',2011,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Coin, pistol, C&C part'),
('Sinestro DCUC Wave 3','Sinestro','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Yellow ring, C&C part'),
('Lex Luthor DCUC Wave 2','Lex Luthor','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Kryptonite, C&C part'),
('Darkseid DCUC Wave 12 C&C','Darkseid','DC Universe Classics','Mattel',2010,'DC Universe Classics Era','9-inch','Modern Age','Rare',79.99,FALSE,'C&C Build-A-Figure'),
('Batman Beyond DCUC Wave 4','Batman Beyond','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Rare',34.99,FALSE,'C&C Despero part'),
('Deathstroke DCUC Wave 7','Deathstroke','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Sword, staff, pistol, C&C part'),
('Harley Quinn DCUC Wave 7','Harley Quinn','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Mallet, pistol, C&C part'),
('Cyborg DCUC Wave 4','Cyborg','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Sonic cannon, C&C part'),
('Booster Gold DCUC Wave 7','Booster Gold','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Skeets, C&C part'),
('Blue Beetle Ted Kord DCUC','Blue Beetle','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Rare',34.99,FALSE,'BB gun, C&C part'),
('Bane DCUC Wave 16','Bane','DC Universe Classics','Mattel',2011,'DC Universe Classics Era','6-inch','Modern Age','Rare',34.99,FALSE,'Venom tube, C&C part'),
('Doomsday DCUC Wave 3','Doomsday','DC Universe Classics','Mattel',2008,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'C&C part'),
('Black Adam DCUC Wave 9','Black Adam','DC Universe Classics','Mattel',2009,'DC Universe Classics Era','6-inch','Modern Age','Uncommon',24.99,FALSE,'Lightning, C&C part'),
-- ════════════════════════════════════════
-- DC COLLECTIBLES NEW 52 / REBIRTH  2012–2019
-- ════════════════════════════════════════
('Batman New 52 DC Collectibles','Batman','DC Comics The New 52','DC Collectibles',2012,'New 52 Era','6.75-inch','New 52','Uncommon',27.99,TRUE,'Batarang, stand'),
('Superman New 52 DC Collectibles','Superman','DC Comics The New 52','DC Collectibles',2012,'New 52 Era','6.75-inch','New 52','Uncommon',27.99,TRUE,'Stand'),
('Wonder Woman New 52 DC Collectibles','Wonder Woman','DC Comics The New 52','DC Collectibles',2012,'New 52 Era','6.75-inch','New 52','Uncommon',27.99,FALSE,'Sword, shield, stand'),
('The Flash New 52 DC Collectibles','The Flash','DC Comics The New 52','DC Collectibles',2012,'New 52 Era','6.75-inch','New 52','Uncommon',27.99,TRUE,'Speed lightning, stand'),
('Green Lantern New 52 DC Collectibles','Green Lantern','DC Comics The New 52','DC Collectibles',2012,'New 52 Era','6.75-inch','New 52','Uncommon',27.99,TRUE,'Ring construct, stand'),
('Aquaman New 52 DC Collectibles','Aquaman','DC Comics The New 52','DC Collectibles',2013,'New 52 Era','6.75-inch','New 52','Uncommon',27.99,FALSE,'Trident, stand'),
('Batman Dark Knight Returns DC Collectibles','Batman','Batman: Dark Knight Returns','DC Collectibles',2014,'New 52 Era','7.25-inch','Classic','Rare',44.99,FALSE,'Batarang, stand'),
('Superman Dark Knight Returns DC Collectibles','Superman','Batman: Dark Knight Returns','DC Collectibles',2014,'New 52 Era','7.25-inch','Classic','Rare',44.99,FALSE,'Stand'),
('Batman Greg Capullo DC Collectibles','Batman','DC Comics Designer Series','DC Collectibles',2014,'New 52 Era','6.75-inch','New 52','Rare',49.99,FALSE,'Batarang, grapple gun, stand'),
('The Joker Greg Capullo DC Collectibles','The Joker','DC Comics Designer Series','DC Collectibles',2014,'New 52 Era','6.75-inch','New 52','Rare',49.99,FALSE,'Severed face, crowbar, stand'),
('Nightwing DC Icons','Nightwing','DC Icons','DC Collectibles',2016,'New 52 Era','6-inch','Modern Age','Uncommon',29.99,TRUE,'Escrima sticks, stand'),
('Batman DC Icons','Batman','DC Icons','DC Collectibles',2016,'New 52 Era','6-inch','Modern Age','Rare',34.99,FALSE,'Batarang, grapple, stand'),
('Deathstroke DC Icons','Deathstroke','DC Icons','DC Collectibles',2016,'New 52 Era','6-inch','Modern Age','Rare',34.99,FALSE,'Sword, staff, stand'),
('Mister Miracle DC Icons','Mr. Miracle','DC Icons','DC Collectibles',2017,'New 52 Era','6-inch','Classic','Rare',44.99,FALSE,'Motherbox, stand'),
('Big Barda DC Icons','Big Barda','DC Icons','DC Collectibles',2017,'New 52 Era','6-inch','Classic','Rare',44.99,FALSE,'Mega-rod, stand'),
('Swamp Thing DC Icons','Swamp Thing','DC Icons','DC Collectibles',2017,'New 52 Era','6-inch','Modern Age','Rare',44.99,FALSE,'Swamp base, stand'),
-- ════════════════════════════════════════
-- MCFARLANE TOYS  2020–2023
-- ════════════════════════════════════════
('Batman Dark Knight Returns McFarlane','Batman','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Classic','Rare',34.99,TRUE,'Batarang, cape, collector card'),
('Batman Zero Year McFarlane','Batman','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','New 52','Common',19.99,TRUE,'Display base, collector card'),
('Batman Rebirth McFarlane','Batman','DC Multiverse','McFarlane Toys',2020,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Batarang, base'),
('Batman Earth -22 Infected McFarlane','Batman','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Dark Multiverse','Ultra Rare',49.99,FALSE,'Dark energy construct, base'),
('Batman Who Laughs McFarlane','Batman','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Dark Multiverse','Ultra Rare',59.99,FALSE,'Dark Batmobile stand, robins'),
('Batman Suit of Sorrows McFarlane','Batman','DC Multiverse','McFarlane Toys',2023,'McFarlane Era','7-inch','Rebirth','Rare',34.99,TRUE,'Sword, shield, collector card'),
('Superman Red Son McFarlane','Superman','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Elseworlds','Rare',34.99,TRUE,'Hammer sickle base'),
('Superman Rebirth McFarlane','Superman','DC Multiverse','McFarlane Toys',2020,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Display base, collector card'),
('Wonder Woman Rebirth McFarlane','Wonder Woman','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Sword, shield, lasso, base'),
('The Flash Rebirth McFarlane','The Flash','DC Multiverse','McFarlane Toys',2020,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Lightning construct, base'),
('The Flash Dark Nights Metal McFarlane','The Flash','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Dark Multiverse','Rare',34.99,TRUE,'Speed force energy, base'),
('Hal Jordan Green Lantern McFarlane','Green Lantern','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Green construct, ring, base'),
('Aquaman Rebirth McFarlane','Aquaman','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Trident, base'),
('The Joker Rebirth McFarlane','The Joker','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Crowbar, base'),
('Harley Quinn Classic McFarlane','Harley Quinn','DC Multiverse','McFarlane Toys',2020,'McFarlane Era','7-inch','Classic','Common',19.99,TRUE,'Mallet, pistol, base'),
('Lex Luthor Apex Predator McFarlane','Lex Luthor','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Rare',34.99,FALSE,'War suit parts, collector card'),
('Deathstroke Rebirth McFarlane','Deathstroke','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Uncommon',24.99,TRUE,'Sword, pistol, staff, base'),
('Bane Knightfall McFarlane','Bane','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Classic','Rare',34.99,TRUE,'Venom tube, base'),
('Darkseid Classic McFarlane','Darkseid','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','10-inch','Classic','Ultra Rare',79.99,FALSE,'Omega beams, throne, base'),
('Nightwing Rebirth McFarlane','Nightwing','DC Multiverse','McFarlane Toys',2020,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Escrima sticks, base'),
('Red Hood Rebirth McFarlane','Red Hood','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Uncommon',24.99,TRUE,'Dual pistols, helmet, base'),
('Batgirl Rebirth McFarlane','Batgirl','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Batarang, grapple gun, base'),
('Black Adam Classic McFarlane','Black Adam','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Classic','Uncommon',24.99,TRUE,'Lightning, base'),
('Shazam Rebirth McFarlane','Shazam','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Lightning construct, base'),
('Cyborg Rebirth McFarlane','Cyborg','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Sonic cannon, base'),
('Green Arrow Rebirth McFarlane','Green Arrow','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Common',19.99,TRUE,'Bow, arrows, quiver, base'),
('Constantine Rebirth McFarlane','John Constantine','DC Multiverse','McFarlane Toys',2023,'McFarlane Era','7-inch','Rebirth','Rare',29.99,TRUE,'Cigarette effect, briefcase'),
('Batman Who Laughs Gold Label McFarlane','Batman','DC Multiverse Gold Label','McFarlane Toys',2022,'McFarlane Era','7-inch','Dark Multiverse','Ultra Rare',49.99,FALSE,'Full accessories set, collector card'),
('Swamp Thing McFarlane','Swamp Thing','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Modern Age','Rare',34.99,TRUE,'Swamp base, vines'),
('Lobo McFarlane','Lobo','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Classic','Rare',34.99,FALSE,'Chain, hook, base'),
('Zatanna McFarlane','Zatanna','DC Multiverse','McFarlane Toys',2023,'McFarlane Era','7-inch','Modern Age','Rare',34.99,TRUE,'Magic wand, top hat, base'),
("Ra's al Ghul Rebirth McFarlane","Ra's al Ghul",'DC Multiverse','McFarlane Toys',2023,'McFarlane Era','7-inch','Rebirth','Rare',29.99,TRUE,'Sword, Lazarus Pit vial'),
('Reverse Flash Rebirth McFarlane','Reverse Flash','DC Multiverse','McFarlane Toys',2021,'McFarlane Era','7-inch','Rebirth','Uncommon',24.99,TRUE,'Speed force energy, base'),
('Scarecrow Rebirth McFarlane','Scarecrow','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Rebirth','Uncommon',21.99,TRUE,'Fear toxin syringe, base'),
('Two-Face Classic McFarlane','Two-Face','DC Multiverse','McFarlane Toys',2023,'McFarlane Era','7-inch','Classic','Uncommon',21.99,TRUE,'Coin, pistols, base'),
('Mr. Freeze Classic McFarlane','Mr. Freeze','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Classic','Uncommon',24.99,FALSE,'Freeze gun, base'),
('Hawkman Rebirth McFarlane','Hawkman','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Rebirth','Uncommon',24.99,TRUE,'Nth metal mace, wings, base'),
('Black Canary Rebirth McFarlane','Black Canary','DC Multiverse','McFarlane Toys',2023,'McFarlane Era','7-inch','Rebirth','Uncommon',24.99,TRUE,'Sonic cry effect, base'),
('Robin Damian Wayne McFarlane','Robin','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Rebirth','Uncommon',21.99,TRUE,'Sword, base'),
('Sinestro Classic McFarlane','Sinestro','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Classic','Uncommon',24.99,TRUE,'Yellow construct, ring, base'),
('Black Manta Rebirth McFarlane','Black Manta','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Rebirth','Uncommon',21.99,TRUE,'Jet pack, blasters, base'),
('Martian Manhunter New 52 McFarlane','Martian Manhunter','DC Multiverse','McFarlane Toys',2023,'McFarlane Era','7-inch','New 52','Uncommon',24.99,TRUE,'Phase effect, base'),
('Superboy Prime McFarlane','Superboy-Prime','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Classic','Rare',34.99,FALSE,'Construct, base'),
('Batman Flashpoint McFarlane','Batman','DC Multiverse','McFarlane Toys',2022,'McFarlane Era','7-inch','Classic','Uncommon',21.99,TRUE,'Two pistols, base');
